[package]
name = "bitcoin"
version = "0.26.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/rust-bitcoin/rust-bitcoin/"
repository = "https://github.com/rust-bitcoin/rust-bitcoin/"
documentation = "https://docs.rs/bitcoin/"
description = "General purpose library for using and interoperating with Bitcoin and other cryptocurrencies."
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"


[features]
default = [ "std", "secp-recovery" ]
base64 = [ "base64-compat" ]
fuzztarget = ["bitcoin_hashes/fuzztarget"]
unstable = []
rand = ["secp256k1/rand-std"]
use-serde = ["serde", "bitcoin_hashes/serde", "secp256k1/serde"]
secp-lowmemory = ["secp256k1/lowmemory"]
secp-recovery = ["secp256k1/recovery"]
std = ["secp256k1/std", "bitcoin_hashes/std", "bech32/std"]
use-bare-io = ["bare-io", "bitcoin_hashes/bare-io"]

[dependencies]
# <<<<<<< HEAD
# bech32 = "0.7.2"
# bitcoin_hashes = { git = "https://github.com/justinmoon/bitcoin_hashes.git", branch = "more_no_std", features = [], default-features = false }
# secp256k1 = "0.20.0"
# =======
base64-compat = { version = "1.0.0", optional = true }
bech32 = { git = "https://github.com/reuvenpo/rust-bech32.git", branch = "support-no_std", features = [], default-features = false }
bitcoin_hashes = { git = "https://github.com/justinmoon/bitcoin_hashes.git", branch = "no_std", features = [], default-features = false }
# FIXME: this used to have recovery and rand-std features enabled
secp256k1 = { git = "https://github.com/justinmoon/rust-secp256k1.git", branch = "no_std", features = [], default-features = false }
# >>>>>>> Update dependencies to actually get rust-bitcoin working on real MCU

base64-compat = { version = "1.0.0", optional = true }
bitcoinconsensus = { version = "0.19.0-1", optional = true }
serde = { version = "1", features = [ "derive" ], optional = true }
bare-io = { version = "0.2", optional = true }

[dev-dependencies]
serde_json = "<1.0.45"
serde_test = "1"
# <<<<<<< HEAD
# secp256k1 = { version = "0.20.0", features = [ "recovery", "rand-std" ] }
# =======
secp256k1 = { git = "https://github.com/justinmoon/rust-secp256k1.git", branch = "no_std", features = ["recovery", "rand-std"], default-features = false }
# >>>>>>> Update dependencies to actually get rust-bitcoin working on real MCU
# We need to pin ryu (transitive dep from serde_json) to stay compatible with Rust 1.22.0
ryu = "<1.0.5"

[[example]]
name = "bip32"

[[example]]
name = "handshake"
required-features = ["std"]
